apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: demo-k8s-clusterstore
spec:
  provider:
    kubernetes:
      remoteNamespace: demo
      server:
        url: https://kubernetes.default.svc
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
          namespace: demo
      auth:
        serviceAccount:
          name: default
          namespace: demo
